# Site settings
title: Benjamin Wilhelm
email: benjamin@b-wilhelm.de
description: >-
  Benjamin Wilhelm's website and blog. Articles about machine learning,
  computer vision, web-development, git and other computer science related
  stuff I discover during my day as a full time nerd.
baseurl: ""
url: ""
date_format: "%Y-%m-%d"
site_source: https://github.com/HedgehogCode/b-wilhelm.de
twitter_username: bewilh
github_username: HedgehogCode

# Front Matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Benjamin Wilhelm"


# Build settings
markdown: kramdown
sass:
  sass_dir: _scss
  style: compressed
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - LICENSE
  - README.md
